[package]
name = "solana-tornado-cash"
version = "0.1.0"
description = "Privacy solution for Solana based on TornadoCash"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "solana_tornado_cash"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.32.1"
anchor-spl = "0.32.1"
spl-token = "4.0.0"
bytemuck = "1.4.0"

[patch.crates-io]
solana-instruction = { version = "2.3.0" }
